project:
  type: book

book:
  title: "Threatened ecosystems of PLACEHOLDER_COUNTRY_NAME"
  subtitle: An IUCN Red List of Ecosystems Assessment
  date: "2000-01-01"
  chapters:
    - index.qmd
    - content/0.1_foreword.qmd
    - content/0.2_preface.qmd
    - content/0.3_acknowledgments.qmd
    - content/0.4_coordinating_orgs.qmd
    - content/0.5_summary.qmd
    - content/1.0_introduction.qmd
    - content/2_ecosystem_overview.qmd
    - references.qmd

bibliography: 
  - references_iucn.bib
  - references_country_specific.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

show-instructions: true

# Content Constants
country-name: PLACEHOLDER_COUNTRY_NAME
country-code: CO  # ISO 3166-1 alpha-2 country code
version: 0.1
year: 2000